In [110]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [111]:
data = pd.read_csv(r'E:\INCEPTEZ\Training\Basics_python\Cabs_Prices.csv')

In [112]:
data[:5]

miles  temp  rain  ncabs  price
0      1    30     0     10     20
1      1    38     0      5     40
2      1    25     0      1     50
3      1    20     1     10     50
4      1    15     1      4     80

In [113]:
data.shape

(60, 5)

In [114]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   miles   60 non-null     int64
 1   temp    60 non-null     int64
 2   rain    60 non-null     int64
 3   ncabs   60 non-null     int64
 4   price   60 non-null     int64
dtypes: int64(5)
memory usage: 2.5 KB


In [115]:
data.describe()

miles       temp       rain      ncabs       price
count  60.000000  60.000000  60.000000  60.000000   60.000000
mean    3.000000  23.350000   0.500000   5.416667  157.683333
std     1.426148   9.166677   0.504219   3.632675  119.883629
min     1.000000  10.000000   0.000000   1.000000   20.000000
25%     2.000000  15.000000   0.000000   2.000000   80.000000
50%     3.000000  21.000000   0.500000   4.500000  123.500000
75%     4.000000  30.000000   1.000000  10.000000  200.250000
max     5.000000  39.000000   1.000000  11.000000  555.000000

In [116]:
data.duplicated().sum()

0

In [117]:
x = data.drop('price',1)

C:\Users\MUTHUK~1\AppData\Local\Temp/ipykernel_12828/3962193891.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = data.drop('price',1)


In [118]:
y =data['price']


In [119]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1,random_state=1)

In [120]:
model = LinearRegression()

In [121]:
model.fit(x_train, y_train)

LinearRegression()

In [122]:
model.coef_

array([47.80785207, -4.40433786, 50.97570474, -9.27742142])

In [123]:
model.intercept_

144.42419166455204

In [124]:
train_pred  =model.predict(x_train)

In [125]:
mean_squared_error(y_train, train_pred)

3963.765203977991

In [126]:
mean_absolute_error(y_train, train_pred)

48.27137102880413

In [127]:
np.sqrt(mean_squared_error(y_train, train_pred))

62.958440291814654

In [128]:
mean_absolute_percentage_error(y_train, train_pred)

0.45353532491436754

### on test data

In [129]:
test_pred =model.predict(x_test)
test_pred

array([105.75029123, 215.20436549,  72.84617574, 101.94257415,
       233.88708341, 172.86621775])

In [130]:
mean_squared_error(y_test, test_pred)

1475.0262664698894

In [131]:
mean_absolute_error(y_test, test_pred)

27.847996131599448

In [132]:
mean_absolute_percentage_error(y_test, test_pred)

0.2707294866263777

In [133]:
np.sqrt(mean_squared_error(y_test, test_pred))

38.406070698131686

### Standardization

In [134]:
scale = StandardScaler()
x =pd.DataFrame(scale.fit_transform(data.drop('price',1)), columns=data.drop('price',1).columns)

C:\Users\MUTHUK~1\AppData\Local\Temp/ipykernel_12828/3244653507.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x =pd.DataFrame(scale.fit_transform(data.drop('price',1)), columns=data.drop('price',1).columns)
C:\Users\MUTHUK~1\AppData\Local\Temp/ipykernel_12828/3244653507.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x =pd.DataFrame(scale.fit_transform(data.drop('price',1)), columns=data.drop('price',1).columns)


In [135]:
y =data['price']

In [136]:
x[:5]

miles      temp  rain     ncabs
0 -1.414214  0.731576  -1.0  1.272344
1 -1.414214  1.611667  -1.0 -0.115668
2 -1.414214  0.181519  -1.0 -1.226077
3 -1.414214 -0.368538   1.0  1.272344
4 -1.414214 -0.918595   1.0 -0.393270

In [137]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1,random_state=1)

In [138]:
model = LinearRegression()

In [139]:
model.fit(x_train, y_train)

LinearRegression()

In [140]:
model.coef_

array([ 67.61051279, -40.03528582,  25.48785237, -33.41982802])

In [141]:
model.intercept_

160.24161179620398

In [142]:
train_pred  =model.predict(x_train)

In [143]:
mean_squared_error(y_train, train_pred)

3963.765203977991

In [144]:
mean_absolute_error(y_train, train_pred)

48.27137102880415

In [145]:
np.sqrt(mean_squared_error(y_train, train_pred))

62.958440291814654

In [146]:
mean_absolute_percentage_error(y_train, train_pred)

0.4535353249143679

### on test data

In [147]:
test_pred =model.predict(x_test)
test_pred

array([105.75029123, 215.20436549,  72.84617574, 101.94257415,
       233.88708341, 172.86621775])

In [148]:
mean_squared_error(y_test, test_pred)

1475.0262664698914

In [149]:
mean_absolute_error(y_test, test_pred)

27.847996131599462

In [150]:
mean_absolute_percentage_error(y_test, test_pred)

0.2707294866263778

In [151]:
np.sqrt(mean_squared_error(y_test, test_pred))

38.406070698131714

### MinMaxScaler

In [153]:
scale = MinMaxScaler()
x =pd.DataFrame(scale.fit_transform(data.drop('price',1)), columns=data.drop('price',1).columns)

C:\Users\MUTHUK~1\AppData\Local\Temp/ipykernel_12828/1487668743.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x =pd.DataFrame(scale.fit_transform(data.drop('price',1)), columns=data.drop('price',1).columns)
C:\Users\MUTHUK~1\AppData\Local\Temp/ipykernel_12828/1487668743.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x =pd.DataFrame(scale.fit_transform(data.drop('price',1)), columns=data.drop('price',1).columns)


In [154]:
y =data['price']

In [155]:
x[:5]

miles      temp  rain  ncabs
0    0.0  0.689655   0.0    0.9
1    0.0  0.965517   0.0    0.4
2    0.0  0.517241   0.0    0.0
3    0.0  0.344828   1.0    0.9
4    0.0  0.172414   1.0    0.3

In [156]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1,random_state=1)

In [157]:
model = LinearRegression()

In [158]:
model.fit(x_train, y_train)

LinearRegression()

In [159]:
model.coef_

array([ 191.23140829, -127.72579803,   50.97570474,  -92.77421419])

In [160]:
model.intercept_

138.91124368705002

In [161]:
train_pred  =model.predict(x_train)

In [162]:
mean_squared_error(y_train, train_pred)

3963.76520397799

In [163]:
mean_absolute_error(y_train, train_pred)

48.27137102880416

In [164]:
np.sqrt(mean_squared_error(y_train, train_pred))

62.95844029181465

In [165]:
mean_absolute_percentage_error(y_train, train_pred)

0.45353532491436854

### on test data

In [166]:
test_pred =model.predict(x_test)
test_pred

array([105.75029123, 215.20436549,  72.84617574, 101.94257415,
       233.88708341, 172.86621775])

In [167]:
mean_squared_error(y_test, test_pred)

1475.0262664698919

In [168]:
mean_absolute_error(y_test, test_pred)

27.847996131599416

In [169]:
mean_absolute_percentage_error(y_test, test_pred)

0.27072948662637736

In [170]:
np.sqrt(mean_squared_error(y_test, test_pred))

38.40607069813172